// <auto-generated />
using EcoWater.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace EcoWater.Migrations
{
    [DbContext(typeof(OracleDbContext))]
    [Migration("20240605022258_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoWater.Models.Embarcacoes", b =>
                {
                    b.Property<int>("Id_Embarcacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Embarcacao"));

                    b.Property<int>("Ano_Fabricação")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Bandeira")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<double>("Capacidade")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<int>("Id_Proprietario")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id_Embarcacao");

                    b.HasIndex("Id_Proprietario");

                    b.ToTable("Embarcacoes");
                });

            modelBuilder.Entity("EcoWater.Models.Incidentes", b =>
                {
                    b.Property<int>("Id_Incidente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Incidente"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Id_Embarcacao")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Severidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Tipo_Poluicao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id_Incidente");

                    b.ToTable("Incidentes");
                });

            modelBuilder.Entity("EcoWater.Models.Monitoramentos", b =>
                {
                    b.Property<int>("Id_Monitoramento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Monitoramento"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Hora")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Id_Embarcacao")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Id_Sensor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nivel_Poluicao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id_Monitoramento");

                    b.HasIndex("Id_Embarcacao");

                    b.HasIndex("Id_Sensor");

                    b.ToTable("Monitoramentos");
                });

            modelBuilder.Entity("EcoWater.Models.Proprietarios", b =>
                {
                    b.Property<int>("Id_Proprietario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Proprietario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id_Proprietario");

                    b.ToTable("Proprietarios");
                });

            modelBuilder.Entity("EcoWater.Models.RegistrosPoluicao", b =>
                {
                    b.Property<string>("Id_Registro")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Hora")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Id_Embarcacao")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Quantidade_Poluida")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Testemunhas")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Tipo_Poluicao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id_Registro");

                    b.ToTable("RegistrosPoluicao");
                });

            modelBuilder.Entity("EcoWater.Models.Sensores", b =>
                {
                    b.Property<int>("Id_Sensor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Sensor"));

                    b.Property<string>("Data_Instalacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id_Sensor");

                    b.ToTable("Sensores");
                });

            modelBuilder.Entity("EcoWater.Models.Embarcacoes", b =>
                {
                    b.HasOne("EcoWater.Models.Proprietarios", "Proprietarios")
                        .WithMany("Embarcacoes")
                        .HasForeignKey("Id_Proprietario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proprietarios");
                });

            modelBuilder.Entity("EcoWater.Models.Monitoramentos", b =>
                {
                    b.HasOne("EcoWater.Models.Embarcacoes", "Embarcacoes")
                        .WithMany()
                        .HasForeignKey("Id_Embarcacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoWater.Models.Sensores", "Sensores")
                        .WithMany()
                        .HasForeignKey("Id_Sensor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Embarcacoes");

                    b.Navigation("Sensores");
                });

            modelBuilder.Entity("EcoWater.Models.Proprietarios", b =>
                {
                    b.Navigation("Embarcacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
